### ISSUE TITLE
Add keyboard shortcut to the app

### ISSUE THREAD

**Issue by siwalikm** [siwalikm/coffitivity-offline#1]
shortcuts required for the following=>
1. pause/play =>**p button and spacebar** 
2. Go to music details page => **right arrow**
3. Go to music list page => **left arrow**
4. minimise app => **esc button**

P.S. No Jquery.. native Javascript only

**Comment by rishpandey** [comment]
I would love to try this.

**Comment by siwalikm** [comment]
@therishabhpandey feel free to give it a try. Btw I would appreciate native javascript, no jQuery.
[this could be a good place to start](https://www.sitepoint.com/community/t/creating-a-vanilla-js-keyboard-shortcut-for-wordpress-control-panel-for-all-wp-websites-i-work-on/265149)

**Comment by rishpandey** [comment]
Ok. Native it is. Cheers.

**Comment by siwalikm** [comment]
closing issue wrt pr => https://github.com/siwalikm/coffitivity-offline/pull/2

**Comment by harshil1712** [comment]
Hey. I am done with the p and left arrow key. Can you let me know what exactly you mean Go to music details page => right arrow. Does it mean that you want to open the page having the player?

**Comment by davidbru** [comment]
as far as I can tell you should change the line 
if(e.keyCode === 80)
to
if(e.keyCode === 80 || e.keyCode === 32)
to also include the spacebar for pausing

**Comment by siwalikm** [comment]
Thanks @davidbru, appreciate your input.
