### ISSUE TITLE
"Coffitivity Offline" cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by donovankeith** [siwalikm/coffitivity-offline#18]
Hi,

I recently downloaded Coffitivity Offline from here:
https://coffitivity-offline.siwalik.in/

I then installed it by opening download and dragging it into my Applications folder.

However, when I attempt to open it, I get the following Mac OS error:

> "Coffitivity Offline" cannot be opened because the developer cannot be verified.
> macOS cannot verify that this app is free from malware.

![image](https://github.com/siwalikm/coffitivity-offline/assets/4267389/cd07d850-e005-443e-bd66-2912181f1d09)

I'm running macOS Sonoma 14.1

**Comment by siwalikm** [comment]
@donovankeith please follow these steps -> https://github.com/siwalikm/coffitivity-offline/wiki/%E2%80%9CCoffitivity-Offline%E2%80%9D-cannot-be-opened-because-the-developer-cannot-be-verified
