### ISSUE TITLE
Tracks arent looping

### ISSUE THREAD

**Issue by jkauszler** [siwalikm/coffitivity-offline#3]
How to replicate:
- Open app
- Select 'Morning Murmur'
- Play until the end of the track ~20-30 minutes.
- The track will finish and not start again.

**Comment by ghost** [comment]
I can pick this up

**Comment by siwalikm** [comment]
@arianahl feel free to contribute. :)

**Comment by ghost** [comment]
Plz check PR #4

**Comment by siwalikm** [comment]
Closing issue wrt https://github.com/siwalikm/coffitivity-offline/pull/4
