### ISSUE TITLE
JS exception

### ISSUE THREAD

**Issue by scotthmurray** [siwalikm/coffitivity-offline#5]
This software is so great! Thank you for making this.

I just downloaded 1.0.1 and got this error after running for a few seconds:

![screen shot 2017-10-16 at 11 01 25 am](https://user-images.githubusercontent.com/1034002/31627235-661fb680-b261-11e7-942e-602f09b9b5d7.png)

Mac OS 10.12.6.  Audio continues to play — it's just that an error appears. Reporting this in case it's helpful.

**Comment by siwalikm** [comment]
Hey @alignedleft, Thanks for reporting this issue.  👍

Seems like this only occurs when you move focus from the app and hit 'esc' key. 
Will be resolved in next release.

p.s. meanwhile you can [use this version (1.0.0)](https://github.com/siwalikm/coffitivity-offline/releases/download/v1.0.0/Coffitivity.Offline-1.0.0.dmg), this version doesn't have this error.

**Comment by siwalikm** [comment]
@larsjanssen6 can you see this?

**Comment by scotthmurray** [comment]
Oh wow! How obscure. Thanks for figuring that out!

**Comment by siwalikm** [comment]
Issue fixed in release 1.0.2
