### ISSUE TITLE
Add version number to info/about screen

### ISSUE THREAD

**Issue by scotthmurray** [siwalikm/coffitivity-offline#6]
Would you consider adding the version number to the About screen? It would make it easier to test and report any issues going forward.

![screen shot 2017-10-16 at 11 03 38 am](https://user-images.githubusercontent.com/1034002/31627306-a6fd28e0-b261-11e7-9545-4eddd930cae4.png)

**Comment by siwalikm** [comment]
Makes sense, feel free to raise a pr for the version text and/or we'll add it in our subsequent release.

**Comment by siwalikm** [comment]
Issue fixed in release 1.0.2
